-- =========================================================
-- Team TODO: 여기에 실제 CREATE TABLE 문을 추가하세요.
-- 예: scenario, simulation_run, grid_cell, weather_observation,
--     weather_forecast, tactical_impact, mission_risk_layer,
--     ugv, operator, event_log, path, path_node, mission_kpi ...
-- =========================================================

-- CREATE TABLE scenario (
--     scenario_id BIGSERIAL PRIMARY KEY,
--     name VARCHAR(255) NOT NULL,
--     weather_scenario VARCHAR(50) NOT NULL
-- );
