"""add_run_asset_statuses_and_simulation_run_new_cols

Revision ID: e8e09d2faebd
Revises: 
Create Date: 2026-04-13 08:31:34.919622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e09d2faebd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission_targets', sa.Column('patrol_duration_sec', sa.Integer(), nullable=False))
    op.add_column('missions', sa.Column('echelon_no', sa.Integer(), nullable=False))
    op.add_column('run_status_snapshots', sa.Column('aoi_remaining_sec', sa.Integer(), nullable=True))
    op.add_column('simulation_runs', sa.Column('selected_mode', sa.String(length=20), nullable=True))
    op.add_column('simulation_runs', sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('simulation_runs', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation_runs', 'acknowledged_at')
    op.drop_column('simulation_runs', 'dispatched_at')
    op.drop_column('simulation_runs', 'selected_mode')
    op.drop_column('run_status_snapshots', 'aoi_remaining_sec')
    op.drop_column('missions', 'echelon_no')
    op.drop_column('mission_targets', 'patrol_duration_sec')
    # ### end Alembic commands ###
